#!/usr/bin/env python3
"""Render a small XYZ molecule as a self-contained launch-ready SVG."""

from __future__ import annotations

import math
import pathlib
import sys


COLORS = {
    "H": "#f8fafc",
    "C": "#334155",
    "N": "#3b82f6",
    "O": "#ef4444",
    "F": "#22c55e",
    "X": "#a78bfa",
}


def read_xyz(path: pathlib.Path) -> list[tuple[str, float, float, float]]:
    lines = [line.strip() for line in path.read_text().splitlines()]
    count = int(lines[0])
    atoms = []
    for line in lines[2 : 2 + count]:
        symbol, x, y, z = line.split()[:4]
        atoms.append((symbol, float(x), float(y), float(z)))
    if len(atoms) != count:
        raise ValueError(f"expected {count} atoms, found {len(atoms)}")
    return atoms


def project(x: float, y: float, z: float) -> tuple[float, float]:
    angle = math.radians(28)
    px = x * math.cos(angle) - y * math.sin(angle)
    py = x * math.sin(angle) + y * math.cos(angle) - z * 0.55
    return px, py


def render(atoms: list[tuple[str, float, float, float]], title: str) -> str:
    projected = [(s, *project(x, y, z), z) for s, x, y, z in atoms]
    xs = [x for _, x, _, _ in projected]
    ys = [y for _, _, y, _ in projected]
    span = max(max(xs) - min(xs), max(ys) - min(ys), 1.0)
    scale = 360.0 / span
    cx = (min(xs) + max(xs)) / 2
    cy = (min(ys) + max(ys)) / 2
    placed = [(s, 400 + (x - cx) * scale, 350 + (y - cy) * scale, z) for s, x, y, z in projected]

    bonds = []
    original = [(s, x, y, z) for s, x, y, z in atoms]
    for i, (_, x1, y1, z1) in enumerate(original):
        for j in range(i + 1, len(original)):
            _, x2, y2, z2 = original[j]
            distance = math.sqrt((x1 - x2) ** 2 + (y1 - y2) ** 2 + (z1 - z2) ** 2)
            # A compact launch renderer, not a bond-perception engine. Avoid
            # the common false-positive H-H edge in small geometries.
            if distance < 1.65 and not (original[i][0] == "H" and original[j][0] == "H"):
                bonds.append((i, j))

    parts = [
        '<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600" viewBox="0 0 800 600" role="img">',
        f"<title>{title}</title>",
        '<defs><filter id="shadow"><feDropShadow dx="0" dy="8" stdDeviation="9" flood-opacity="0.35"/></filter></defs>',
        '<rect width="800" height="600" rx="28" fill="#08111f"/>',
        f'<text x="48" y="64" fill="#f8fafc" font-family="Inter,Helvetica,sans-serif" font-size="32" font-weight="700">{title}</text>',
        '<text x="48" y="98" fill="#94a3b8" font-family="Inter,Helvetica,sans-serif" font-size="18">Generated by Tyr · rendered from XYZ</text>',
    ]
    for i, j in bonds:
        _, x1, y1, _ = placed[i]
        _, x2, y2, _ = placed[j]
        parts.append(f'<line x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" y2="{y2:.1f}" stroke="#64748b" stroke-width="18" stroke-linecap="round"/>')
    for symbol, x, y, z in sorted(placed, key=lambda atom: atom[3]):
        radius = 34 if symbol == "H" else 46
        color = COLORS.get(symbol, "#f59e0b")
        parts.append(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="{radius}" fill="{color}" stroke="#e2e8f0" stroke-width="4" filter="url(#shadow)"/>')
        parts.append(f'<text x="{x:.1f}" y="{y + 8:.1f}" fill="#020617" font-family="Inter,Helvetica,sans-serif" font-size="24" font-weight="800" text-anchor="middle">{symbol}</text>')
    parts.extend([
        f'<text x="48" y="552" fill="#cbd5e1" font-family="SFMono-Regular,Menlo,monospace" font-size="18">atoms={len(atoms)} · bonds={len(bonds)}</text>',
        '</svg>',
    ])
    return "\n".join(parts)


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit("usage: render_xyz.py input.xyz output.svg")
    source = pathlib.Path(sys.argv[1])
    destination = pathlib.Path(sys.argv[2])
    destination.write_text(render(read_xyz(source), source.stem.replace("_", " ").title()))
    print(f"wrote {destination}")


if __name__ == "__main__":
    main()
